[package]
name = "rust_leetcode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[ bin ]] 
name = "leetcode" 
path = "src/10.正则表达式匹配.rs"  